---
title: "Publications"
output:
  html_document:
    fig_cap: yes
    highlight: tango
    smooth_scroll: no
    theme: cosmo
    toc: yes
    toc_float: yes
    toc_position: right
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Some publications include a file link. Unfortunately, in most cases my draft was heavily revised after review, and publishers prohibit publicly sharing the end result. Feel free to send me an email in case you cannot find a particular file here. Papers and chapters are sorted first by alphabet (based on authors' surnames) and second by year in descending order.[^1] Talks are ordered chronologically.

Updated: `r Sys.Date()`

[^1]: In Russian my last name can be transcribed as Ферхеес (Ferxees), Ферхейс (Ferxejs) or Верхейс (Verxejs).

<br>

### Papers and chapters

* Alexeyev, Mikhail and Samira Verhees. <span style="color: #CC0066;">To appear.</span> 'Botlikh'. In Yury Koryakov and Timur Maisak (eds.) *Handbook of Caucasian Languages. Vol. 2. Nakh-Daghestanian.* Berlin/New York: De Gruyter Mouton. [Draft](https://github.com/sverhees/site/blob/master/papers/botlikhgrammar_draft.pdf)

* Chechuro, Ilia, Michael Daniel, and Samira Verhees. 2021. Small-scale multilingualism through the prism of lexical borrowing. *Journal of Bilingualism* 25(4), 1019--1039. [DOI](https://doi.org/10.1177%2F13670069211023141) | [Draft](https://www.academia.edu/44322050/Small_scale_multilingualism_through_the_prism_of_lexical_borrowing) 

* Daniel, Michael, Ilia Chechuro, Samira Verhees, and Nina Dobrushina. 2021. 'Lingua francas as lexical donors: evidence from Daghestan'. *Language* 97.3, 520--560. [DOI](https://doi.org/10.1353/lan.2021.0046) | [Draft](https://www.academia.edu/44322048/Lingua_francas_as_lexical_donors_Evidence_from_Daghestan)

* Daniel, Michael, Nina Dobrushina, Polina Kazakova, Ilya Schurov, Vasilisa Zhigulskaya, Alexei Vinyar, Daria Ignatenko, Ekaterina Makhlina, Ruprecht von Waldenfels, Alexandra Ter-Avanesova, Ekaterina Gerasimenko, Maria Tsfasman, Samira Verhees, Sergey Say and Maria Ovsjannikova. 2019. 'Dialect loss in the Russian North: modeling change across variables' *Language Variation and Change.* Vol. 31(3), 353--376. [DOI](https://doi.org/10.1017/S0954394519000243)

* Kaye, Steven, Aleksandra Martynova, George Moroz, Neige Rochant, Samira Verhees and Aigul Zakirova. <span style="color: #CC0066;">To appear</span>. 'Andi (Zilo)'. In Yury Koryakov and Timur Maisak (eds.) *Handbook of Caucasian Languages. Vol. 2. Nakh-Daghestanian.* Berlin/New York: De Gruyter Mouton.

* Maisak, Timur and Samira Verhees. 2024. 'The ‘Still Not’ Present in Andi: identifying the grammaticalization source'. *Folia Linguistica*, vol. 58, no. s45-s1, 185--220. [DOI](https://doi.org/10.1515/flin-2024-2007)

* Moroz, George and Samira Verhees. 2019. 'Variability in noun classes assignment in Zilo Andi: experimental data'. *Iran and the Caucasus.* Vol. 23(3), 268--282. [DOI](https://doi.org/10.1163/1573384X-20190306)

* Naccarato, Chiara, George Moroz and Samira Verhees. <span style="color: #CC0066;">To appear</span>. 'Godoberi'. In Yury Koryakov and Timur Maisak (eds.) *Handbook of Caucasian Languages. Vol. 2. Nakh-Daghestanian.* Berlin/New York: De Gruyter Mouton.

* Verhees, Samira. 2024. 'Social networks for academics'. *Journal of the Field Linguists Society* 1. [DOI](https://doi.org/10.5281/zenodo.10611237)
* Verhees, Samira. 2023. 'The role of multilingualism in narratives in Botlikh (Dagestan)'. In Nina Sumbatova, Ivan Kapitonov, Maria Khachaturyan, Sofia Oskolskaya, Samira Verhees (eds.) *Songs and trees: papers in memory of Sasha Vydrina*. St. Petersburg: Institute for Linguistic Studies Russian Academy of Sciences, 425--450. [URL](http://sashavydrina.tilda.ws/inmemoriam)
* Verhees, Samira. 2021.  'Evidentiality in East Caucasian on the map.' *Languages of the Caucasus* 5. [DOI](https://doi.org/10.5070/L95054646) | [URL](https://escholarship.org/uc/item/1zf7z1ck)
* Verhees, Samira. 2020. 'Evidentiality in the Rikvani dialect of Andi'. *Iran and the Caucasus.* Vol 24(4), 309-324. [DOI](http://doi.org/10.1163/1573384X-20200305)
* Verhees, Samira. 2019. 'Defining evidentiality'. *Voprosy jazykoznanija* 2019(6), 113--133. [DOI](https://ras.jes.su/vopjaz/s0373658x0007549-2-1) | [PDF](https://vja.ruslang.ru/ru/archive/2019-6/113-133)
* Verhees, Samira. 2019. 'General converbs in Andi'. *Studies in language* Vol. 43(1), 195--230. [DOI](https://doi.org/10.1075/sl.18026.ver)
* Verhees, Samira. 2018. 'Chapter 12. The perfect in Avar and Andi: Cross-linguistic variation among two closely-related East Caucasian languages'. In Dalila Ayoun, Agnès Celle and Laure Lansari (eds.) *Tense, Aspect, Modality and Evidentiality: Cross-linguistic perspectives.* Amsterdam : John Benjamins, 261--280. [DOI](https://doi.org/10.1075/slcs.197.12ver)
* Verhees, Samira. 2018. '[Review] S. E. Murray. The semantics of evidentials. (Oxford Studies in Semantics and Pragmatics, 9.) Oxford: Oxford University Press, 2017. 192 p. ISBN 978-0-19- 968157-0.' *Voprosy Jazykoznanija* 2018(3), 154--160. [DOI](https://www.libnauka.ru/item.php?doi=10.7868/S0373658X1803008X) | [PDF](https://vja.ruslang.ru/ru/archive/2018-3/154-160)

* Наккарато, Кьяра и Самира Ферхеес. 2021. 'Доброе утро, проснулись? Утренние приветствия в языках Дагестана' [Good morning, did you wake up? Morning greetings in the languages of Dagestan]. Тимур Майсак, Нина Сумбатова, Яков Тестелец (ред.) *Дурхъаси хазна. Сборник статей к 60-летию Р. О. Муталова*. Москва: Буки Веди, 283--298.
* Пеетерс-Подгаевская, Алла и Самира Ферхейс. 2014. 'В мире этом всё -- как коленце бамбука: японское хайку в современной русской поэзии' [Everything in this world is like a bamboo knuckle: Japanese haiku in contemporary Russian poetry]. Wim Honselaar, Jenny Stelleman and Willem Weststeijn (eds.) *To the point: Festschrift for Eric de Haard on the occasion of his 65th birthday*. Amsterdam: Pegasus, 275--297.  [PDF](https://pure.uva.nl/ws/files/2071110/164846_Xajku_in_Russische_poezie.pdf)

* Ферхеес, Самира. 2019. *Эвиденциальность как часть видо-временной системы в нахско-дагестанских языках [Evidentiality as part of tense-aspect in East Caucasian languages]*. НИУ ВШЭ Москва: Диссертация. [Repository](https://github.com/sverhees/dissertation_evidentiality)
* Ферхеес, Самира. 2018. 'К происхождению эвиденциальности в нахско-дагестанских языках: структурные и ареальные перспективы' [Towards the origin of evidentiality in Nakh-Daghestanian languages: structural and areal perspectives]. *Вестник ПСТГУ Серия 3: Филология*. 2018(57), 110--123. [DOI](http://doi.org/10.15382/sturIII201857.110-123) | [PDF](http://periodical.pstgu.ru/en/pdf/article/6766)
* Ферхеес, Самира. 2017. 'Эвиденциальность и перфект в рутульском языке (на материале говора с. Кина) [Evidentiality and the perfect in Rutul (based on the dialect of the village Kina)]'. Марина Федина (ред.) *Электронная письменность народов РФ: опыт, проблемы и перспективы. Сборник материалов научной конференции, 16--17 марта 2017г., Сыктывкар*. Syktyvkar: KRAGSiU, 228--235. [PDF](https://github.com/sverhees/site/blob/master/papers/Rutul_perfect_paper.pdf)

<br>

### Talks

#### 2022

* 'Time nouns and temporal constructions in the languages of Dagestan' (w. Timur Maisak). *Second International Conference Anatolia-The Caucasus-Iran*, 21.06.2022, Russian-Armenian University, Yerevan. [PDF](https://github.com/sverhees/site/blob/master/talks/2022Yerevan_Timenouns.pdf)

#### 2021

* 'Типологический атлас языков Дагестана -- проблемы и перспективы' (с Т. А. Мухиным и М. К. Наккарато) [Typological atlas of the languages of Dagestan. Problems and perspectives (w. T. Mukhin and C. Naccarato)]. *Актуальные проблемы изучения кавказских языков*, 15.12.2021, Dagestan State University, Makhachkala.

* 'Animacy agreement in non-verbal predication in Botlikh' at *Eighteenth conference on typology and grammar for young scholars*, 25--27.11.2021, Institute of Linguistic Studies RAS, St. Petersburg (online) | [PDF and data](https://github.com/sverhees/2021mt_negcop/blob/master/2021mt_negative_copulas.pdf)

* 'Linguistic geography of East Caucasian languages' with Yuri Koryakov at *[Online course on East Caucasian languages](https://ilcl.hse.ru/en/east_caucasian/)*, 3.11.2021 Linguistic Convergence Laboratory, HSE University Moscow | [PDF and video](https://ilcl.hse.ru/en/east_caucasian/lectures)

* ‘Typological Atlas of the Languages of Daghestan’ with Michael Daniel, Timofey Mukhin, and Chiara Naccarato at *LACIM Webinar*, 10.05.2021, INALCO Paris (online).

* ‘Reported speech in Botlikh’ at *A data oriented workshop: The grammatical variation of reported speech across languages*, 14.01.2021, University of Helsinki (online). 


#### 2020

* 'Reported speech in Botlikh' at *Seventeenth conference on typology and grammar for young scholars* 19--21.11.2020 Institute of Linguistic Studies RAS, St. Petersburg (online) | [PDF](https://github.com/sverhees/site/blob/master/talks/2020MT_RS_in_Botlikh.pdf)

* 'The encoding of evidentiality in East Caucasian: different types of marking and areal distribution' at [Online course on East Caucasian languages](https://ilcl.hse.ru/en/east_caucasian/), 18.11.2020 Linguistic Convergence Laboratory, HSE University Moscow | [PDF and video](https://ilcl.hse.ru/en/east_caucasian/2020)

* 'Catching variation during fieldwork on Daghestanian languages' with George Moroz at *Dialectology and linguistic geography*, 24.04.2020 RSUH, Moscow | [PDF and data](https://github.com/agricolamz/2020.04.24_RSUH_Zilo_variation)

#### 2019

* 'Evidentiality as an areal feature: an East Caucasian perspective on typology vs. reality' at *Workshop language sampling: issues and challenges*, 20.12.2019 Institute of Linguistics RAS, St. Petersburg | [PDF and data](https://github.com/sverhees/2019_spbsampling)

* 'Towards a tentative origin of animacy markers in Botlikh' with Chiara Naccarato at *Caucasian languages: typology and diachrony*, 23--24.10.2019 Institute of Linguistics RAS, Moscow | [PDF and data](https://github.com/sverhees/2019_Animacy-origin)

* 'Variation in two dictionaries of Botlikh' with Chiara Naccarato and George Moroz at *Документирование языков и диалектов коренных малочисленных народов России*, 14--16.10.2019 Institute of Linguistics RAS, St. Petersburg | [PDF](https://github.com/sverhees/site/blob/master/talks/2019_Botlikh_dictionaries.pdf)

* 'Ordinal numerals and animacy in Botlikh' (with Chiara Naccarato)[^2] at *SLE*, 21--24.08.2019, Leipzig University | [PDF and data](https://github.com/sverhees/2019sle_ordinals)

[^2]: Chiara joined me on this project after the abstract had been accepted. I added her name on the slides because she did a lot of the work for this talk.

* 'Narrative use: a measurable feature of evidentiality as a meaning of the perfect' at *16th international pragmatics conference*, 9--14.06.2019, Hong Kong Polytech University


#### 2018

* 'Time and time again: the evolution of 'time' nouns into temporal clause markers in three Daghestanian languages' with George Moroz at *Fifteenth conference on typology and grammar for young scholars*, 22--24.11.2018, Institute of Linguistics RAS, St. Petersburg | [PDF and data](https://github.com/sverhees/2018time)

* 'Counterexpectation present in Andi. Discerning the grammaticalization source' with Timur Maisak at *Chronos 13*, 04--06.06.2018, University of Neuchâtel | [PDF](https://www.academia.edu/36777985/Counterexpectation_Present_in_Andi)

* 'Gender attribution of borrowings and native lexemes in Zilo (Andi)' with George Moroz at *Anatolia-the Caucasus-Iran: Ethnic and Linguistic Contacts*, 10--12.05.2018, Insitute of Oriental Studies, Yerevan | [Slides and data](https://github.com/agricolamz/2018.05.11_Yerevan_Zilo_classes)

#### 2017

* 'Evidentiality in the Rikwani dialect of Andi' at *Fourteenth conference on typology and grammar for young scholars*, 23--25.11.2017, Institute of Linguistics RAS, St. Petersburg

* 'Evidentiality and the perfect in the Rikwani and Zilo dialects of Andi (East Caucasian)' at *SLE*, 10--13.09.2017, Zürich University | [PDF](https://github.com/sverhees/SLE2017)

* 'The (auxiliary) verb *b-iʁidu* in Andi' with Neige Rochant, *Historical linguistics of the Caucasus*, 12--14.04.2017, Paris | [PDF](https://www.academia.edu/33113058/The_auxiliary_verb_b-i%CA%81idu_in_Andi_Historical_Linguistics_of_the_Caucasus_-_April_12-14_2017_)

* 'Эвиденциальность и перфект в рутульском языке (на материале говора с. Кина)' [Evidentiality and the perfect in Rutul (based on the dialect of the village Kina)]' at *Élektronnaja pis'mennost' narodov RF: opyt, problemy i perspektivy*, 16--17.03.2017, Syktyvkar

#### 2016

* 'Evidentiality and other usages of the perfect in two Nakh-Daghestanian languages' at *Tense, aspect, modality, evidentiality: comparative, cognitive, theoretical, applied perspectives*, 16--17.11.2016, Diderot University

<br>

### Posters

* 'Суффиксы направленности -ку и -ру в ботлихском языке' (с С.Х. Задыкян и К. Наккарато) [Directional suffixes -ku and -ru in Botlikh (w. S. Zadykian and C. Naccarato)]. *Малые языки в большой лингвистике*, МГУ имени Ломоносова 2020 | [PDF](https://github.com/sverhees/site/tree/master/other/MYABL2020_Elative_cases_Botlikh.pdf)

* 'Lexical influence of Avar on minority languages of Daghestan' *Summer School areal linguistics and languages of Russia*, HSE Moscow 2018 | [PDF and data](https://github.com/sverhees/2018_Areal_AvarInfluence)

* 'Perfectoids and evidentiality in East Caucasian' at *LOT Winter school*, VU Amsterdam 2018 | [PDF](https://github.com/sverhees/site/blob/master/other/Verhees_LOT2018_Areal_evidentiality_East_Caucasian.pdf)

<br>

### Other

* Verhees, Samira. 2021. 'Negative copulas, animacy and demonstratives in Botlikh (with some notes on Miarso).
Fieldwork report April 2021' | [PDF](https://github.com/sverhees/fieldtrip_spring2021/blob/main/negative_copulas_field_report.pdf)

* Naccarato, Chiara and Samira Verhees. 2021. 'Animacy in Botlikh' (Handout) | [PDF](https://github.com/sverhees/site/blob/master/other/Animacy_in_Botlikh.pdf)

* Moroz, George and Samira Verhees. 2020. *East Caucasian villagest dataset v2.0*. Moscow: International Convergence Laboratory NRU HSE. [Repository](https://github.com/sverhees/master_villages) | [DOI](https://doi.org/10.5281/zenodo.5588473)

* Chechuro, Ilya, Michael Daniel, Nina Dobrushina and Samira Verhees. 2019. *Daghestanian loans database.* Linguistic Convergence Laboratory, HSE. [URL](https://lingconlab.github.io/Dagloan_database/DL_database.html) | [DOI](https://zenodo.org/record/2616530).

* Verhees, Samira. 2019. 'Demonstratives in Zilo Andi' (Handout) | [PDF](https://github.com/sverhees/site/blob/master/other/Zilo_demonstratives.pdf)

